name: emotcare_apps
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  bloc: ^9.1.0
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dotted_border: ^3.1.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^9.2.4
  flutter_svg_provider: ^1.0.7
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  go_router: ^16.2.5
  google_fonts: ^6.3.2
  http: ^1.5.0
  intl: ^0.20.2
  local_auth: ^2.3.0
  permission_handler: ^12.0.1
  webview_flutter: ^4.13.0
  youtube_player_flutter: ^9.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env

flutter_launcher_icons:
  android: "emotecare_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21
